name: Daily Test Run

on:
  schedule:
    - cron: '0 9 * * *'  # runs daily at 9 AM UTC
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          echo "Running daily tests..."
          exit 0
